package com.equivida.intranet.clientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Mon Apr 20 11:00:12 COT 2020
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://ws.equivida.com/", name = "RcsWs")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RcsWs {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://ws.equivida.com/", partName = "return")
    public RcsRespuestaDtoArray buscarRcs(
        @WebParam(partName = "arg0", name = "arg0")
        PersonaDtoArray arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );
}
