//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.20 at 03:09:10 PM ECT 
//


package com.equivida.databook.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.equivida.databook.model2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.equivida.databook.model2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Registros.Sri }
     * 
     */
    public Registros.Sri createRegistrosSri() {
        return new Registros.Sri();
    }

    /**
     * Create an instance of {@link Registros.Cedulaspadres }
     * 
     */
    public Registros.Cedulaspadres createRegistrosCedulaspadres() {
        return new Registros.Cedulaspadres();
    }

    /**
     * Create an instance of {@link Registros.PrimeroAnterior }
     * 
     */
    public Registros.PrimeroAnterior createRegistrosPrimeroAnterior() {
        return new Registros.PrimeroAnterior();
    }

    /**
     * Create an instance of {@link Registros.Vehicular }
     * 
     */
    public Registros.Vehicular createRegistrosVehicular() {
        return new Registros.Vehicular();
    }

    /**
     * Create an instance of {@link Registros.Padres }
     * 
     */
    public Registros.Padres createRegistrosPadres() {
        return new Registros.Padres();
    }

    /**
     * Create an instance of {@link Registros.Actual }
     * 
     */
    public Registros.Actual createRegistrosActual() {
        return new Registros.Actual();
    }

    /**
     * Create an instance of {@link Registros }
     * 
     */
    public Registros createRegistros() {
        return new Registros();
    }

    /**
     * Create an instance of {@link Registros.Civil }
     * 
     */
    public Registros.Civil createRegistrosCivil() {
        return new Registros.Civil();
    }

    /**
     * Create an instance of {@link Registros.Conyuge }
     * 
     */
    public Registros.Conyuge createRegistrosConyuge() {
        return new Registros.Conyuge();
    }

    /**
     * Create an instance of {@link Registros.SegundoAnterior }
     * 
     */
    public Registros.SegundoAnterior createRegistrosSegundoAnterior() {
        return new Registros.SegundoAnterior();
    }

    /**
     * Create an instance of {@link Registros.Conyugecedula }
     * 
     */
    public Registros.Conyugecedula createRegistrosConyugecedula() {
        return new Registros.Conyugecedula();
    }

    /**
     * Create an instance of {@link Registros.Contactabilidad }
     * 
     */
    public Registros.Contactabilidad createRegistrosContactabilidad() {
        return new Registros.Contactabilidad();
    }

    /**
     * Create an instance of {@link Registros.Hijos }
     * 
     */
    public Registros.Hijos createRegistrosHijos() {
        return new Registros.Hijos();
    }

}
