//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.20 at 03:09:10 PM ECT 
//

package com.equivida.databook.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="civil">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cedula" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="primernombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="segundonombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="primerapellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="segundoapellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombreconyuge" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombrepadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombremadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="profesion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nacionalidad" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="dianacimiento" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="mesnacimiento" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="anionacimiento" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="estadocivil" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="genero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="diamatrimonio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mesmatrimonio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="aniomatrimonio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="diadefuncion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mesdefuncion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="aniodefuncion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="actual">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nombreempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rucempleador" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="direccionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="actividadempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="salariopromedio" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="salarioactual" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="telefonoempleador" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="mesespromedio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="fechaentrada" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechasalida" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="descripcionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="primeroAnterior">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nombreempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rucempleador" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="descripcionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="direccionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="actividadempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="provinciaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="parroquiaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cantonempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechaentradaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechasalidaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cargoempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="salarioempleador" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="telefonoempleador" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="segundoAnterior">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nombreempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rucempleador" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="descripcionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="direccionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="actividadempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="provinciaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="parroquiaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cantonempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechaentradaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechasalidaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cargoempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="salarioempleador" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="telefonoempleador" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sri">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rucpersonanatual" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="razonsocial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombrefantasia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="actividad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="calle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="interseccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="referencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="obligado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="fechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="suspension" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reinicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contactabilidad">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tel1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="tel2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="tel3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tel4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tel5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vehicular">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="placa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="hijos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="hijo1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hijo2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hijo3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hijo4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hijo5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hijo6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hijo7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hijo8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="conyuge">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="conyugenombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="conyugecedula">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="conyugecedula" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="padres">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nombrepadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombremadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cedulaspadres">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tipo1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cedtipo1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tipo2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cedtipo2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "civil", "actual", "primeroAnterior", "segundoAnterior", "sri", "contactabilidad",
		"vehicular", "hijos", "conyuge", "conyugecedula", "padres", "cedulaspadres" })
@XmlRootElement(name = "registros")
public class Registros {

	@XmlElement(required = true)
	protected Registros.Civil civil;
	@XmlElement(required = true)
	protected Registros.Actual actual;
	@XmlElement(required = true)
	protected Registros.PrimeroAnterior primeroAnterior;
	@XmlElement(required = true)
	protected Registros.SegundoAnterior segundoAnterior;
	@XmlElement(required = true)
	protected Registros.Sri sri;
	@XmlElement(required = true)
	protected Registros.Contactabilidad contactabilidad;
	@XmlElement(required = true)
	protected Registros.Vehicular vehicular;
	@XmlElement(required = true)
	protected Registros.Hijos hijos;
	@XmlElement(required = true)
	protected Registros.Conyuge conyuge;
	@XmlElement(required = true)
	protected Registros.Conyugecedula conyugecedula;
	@XmlElement(required = true)
	protected Registros.Padres padres;
	@XmlElement(required = true)
	protected Registros.Cedulaspadres cedulaspadres;

	/**
	 * Gets the value of the civil property.
	 * 
	 * @return possible object is {@link Registros.Civil }
	 * 
	 */
	public Registros.Civil getCivil() {
		return civil;
	}

	/**
	 * Sets the value of the civil property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Civil }
	 * 
	 */
	public void setCivil(Registros.Civil value) {
		this.civil = value;
	}

	/**
	 * Gets the value of the actual property.
	 * 
	 * @return possible object is {@link Registros.Actual }
	 * 
	 */
	public Registros.Actual getActual() {
		return actual;
	}

	/**
	 * Sets the value of the actual property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Actual }
	 * 
	 */
	public void setActual(Registros.Actual value) {
		this.actual = value;
	}

	/**
	 * Gets the value of the primeroAnterior property.
	 * 
	 * @return possible object is {@link Registros.PrimeroAnterior }
	 * 
	 */
	public Registros.PrimeroAnterior getPrimeroAnterior() {
		return primeroAnterior;
	}

	/**
	 * Sets the value of the primeroAnterior property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.PrimeroAnterior }
	 * 
	 */
	public void setPrimeroAnterior(Registros.PrimeroAnterior value) {
		this.primeroAnterior = value;
	}

	/**
	 * Gets the value of the segundoAnterior property.
	 * 
	 * @return possible object is {@link Registros.SegundoAnterior }
	 * 
	 */
	public Registros.SegundoAnterior getSegundoAnterior() {
		return segundoAnterior;
	}

	/**
	 * Sets the value of the segundoAnterior property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.SegundoAnterior }
	 * 
	 */
	public void setSegundoAnterior(Registros.SegundoAnterior value) {
		this.segundoAnterior = value;
	}

	/**
	 * Gets the value of the sri property.
	 * 
	 * @return possible object is {@link Registros.Sri }
	 * 
	 */
	public Registros.Sri getSri() {
		return sri;
	}

	/**
	 * Sets the value of the sri property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Sri }
	 * 
	 */
	public void setSri(Registros.Sri value) {
		this.sri = value;
	}

	/**
	 * Gets the value of the contactabilidad property.
	 * 
	 * @return possible object is {@link Registros.Contactabilidad }
	 * 
	 */
	public Registros.Contactabilidad getContactabilidad() {
		return contactabilidad;
	}

	/**
	 * Sets the value of the contactabilidad property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Contactabilidad }
	 * 
	 */
	public void setContactabilidad(Registros.Contactabilidad value) {
		this.contactabilidad = value;
	}

	/**
	 * Gets the value of the vehicular property.
	 * 
	 * @return possible object is {@link Registros.Vehicular }
	 * 
	 */
	public Registros.Vehicular getVehicular() {
		return vehicular;
	}

	/**
	 * Sets the value of the vehicular property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Vehicular }
	 * 
	 */
	public void setVehicular(Registros.Vehicular value) {
		this.vehicular = value;
	}

	/**
	 * Gets the value of the hijos property.
	 * 
	 * @return possible object is {@link Registros.Hijos }
	 * 
	 */
	public Registros.Hijos getHijos() {
		return hijos;
	}

	/**
	 * Sets the value of the hijos property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Hijos }
	 * 
	 */
	public void setHijos(Registros.Hijos value) {
		this.hijos = value;
	}

	/**
	 * Gets the value of the conyuge property.
	 * 
	 * @return possible object is {@link Registros.Conyuge }
	 * 
	 */
	public Registros.Conyuge getConyuge() {
		return conyuge;
	}

	/**
	 * Sets the value of the conyuge property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Conyuge }
	 * 
	 */
	public void setConyuge(Registros.Conyuge value) {
		this.conyuge = value;
	}

	/**
	 * Gets the value of the conyugecedula property.
	 * 
	 * @return possible object is {@link Registros.Conyugecedula }
	 * 
	 */
	public Registros.Conyugecedula getConyugecedula() {
		return conyugecedula;
	}

	/**
	 * Sets the value of the conyugecedula property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Conyugecedula }
	 * 
	 */
	public void setConyugecedula(Registros.Conyugecedula value) {
		this.conyugecedula = value;
	}

	/**
	 * Gets the value of the padres property.
	 * 
	 * @return possible object is {@link Registros.Padres }
	 * 
	 */
	public Registros.Padres getPadres() {
		return padres;
	}

	/**
	 * Sets the value of the padres property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Padres }
	 * 
	 */
	public void setPadres(Registros.Padres value) {
		this.padres = value;
	}

	/**
	 * Gets the value of the cedulaspadres property.
	 * 
	 * @return possible object is {@link Registros.Cedulaspadres }
	 * 
	 */
	public Registros.Cedulaspadres getCedulaspadres() {
		return cedulaspadres;
	}

	/**
	 * Sets the value of the cedulaspadres property.
	 * 
	 * @param value
	 *            allowed object is {@link Registros.Cedulaspadres }
	 * 
	 */
	public void setCedulaspadres(Registros.Cedulaspadres value) {
		this.cedulaspadres = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="nombreempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="rucempleador" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *         &lt;element name="direccionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="actividadempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="salariopromedio" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="salarioactual" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="telefonoempleador" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="mesespromedio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="fechaentrada" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="fechasalida" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="descripcionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "nombreempleador", "rucempleador", "direccionempleador", "actividadempleador",
			"cargo", "provincia", "canton", "parroquia", "salariopromedio", "salarioactual", "telefonoempleador",
			"mesespromedio", "fechaentrada", "fechasalida", "descripcionempleador" })
	public static class Actual {

		@XmlElement(required = true)
		protected String nombreempleador;
		protected String rucempleador;
		@XmlElement(required = true)
		protected String direccionempleador;
		@XmlElement(required = true)
		protected String actividadempleador;
		@XmlElement(required = true)
		protected String cargo;
		protected String provincia;
		protected String canton;
		protected String parroquia;
		protected short salariopromedio;
		protected short salarioactual;
		protected String telefonoempleador;
		protected byte mesespromedio;
		@XmlElement(required = true)
		protected String fechaentrada;
		@XmlElement(required = true)
		protected String fechasalida;
		@XmlElement(required = true)
		protected String descripcionempleador;

		/**
		 * Gets the value of the nombreempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombreempleador() {
			return nombreempleador;
		}

		/**
		 * Sets the value of the nombreempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombreempleador(String value) {
			this.nombreempleador = value;
		}

		/**
		 * Gets the value of the rucempleador property.
		 * 
		 */
		public String getRucempleador() {
			return rucempleador;
		}

		/**
		 * Sets the value of the rucempleador property.
		 * 
		 */
		public void setRucempleador(String value) {
			this.rucempleador = value;
		}

		/**
		 * Gets the value of the direccionempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDireccionempleador() {
			return direccionempleador;
		}

		/**
		 * Sets the value of the direccionempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDireccionempleador(String value) {
			this.direccionempleador = value;
		}

		/**
		 * Gets the value of the actividadempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getActividadempleador() {
			return actividadempleador;
		}

		/**
		 * Sets the value of the actividadempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setActividadempleador(String value) {
			this.actividadempleador = value;
		}

		/**
		 * Gets the value of the cargo property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCargo() {
			return cargo;
		}

		/**
		 * Sets the value of the cargo property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCargo(String value) {
			this.cargo = value;
		}

		/**
		 * Gets the value of the provincia property.
		 * 
		 */
		public String getProvincia() {
			return provincia;
		}

		/**
		 * Sets the value of the provincia property.
		 * 
		 */
		public void setProvincia(String value) {
			this.provincia = value;
		}

		/**
		 * Gets the value of the canton property.
		 * 
		 */
		public String getCanton() {
			return canton;
		}

		/**
		 * Sets the value of the canton property.
		 * 
		 */
		public void setCanton(String value) {
			this.canton = value;
		}

		/**
		 * Gets the value of the parroquia property.
		 * 
		 */
		public String getParroquia() {
			return parroquia;
		}

		/**
		 * Sets the value of the parroquia property.
		 * 
		 */
		public void setParroquia(String value) {
			this.parroquia = value;
		}

		/**
		 * Gets the value of the salariopromedio property.
		 * 
		 */
		public short getSalariopromedio() {
			return salariopromedio;
		}

		/**
		 * Sets the value of the salariopromedio property.
		 * 
		 */
		public void setSalariopromedio(short value) {
			this.salariopromedio = value;
		}

		/**
		 * Gets the value of the salarioactual property.
		 * 
		 */
		public short getSalarioactual() {
			return salarioactual;
		}

		/**
		 * Sets the value of the salarioactual property.
		 * 
		 */
		public void setSalarioactual(short value) {
			this.salarioactual = value;
		}

		/**
		 * Gets the value of the telefonoempleador property.
		 * 
		 */
		public String getTelefonoempleador() {
			return telefonoempleador;
		}

		/**
		 * Sets the value of the telefonoempleador property.
		 * 
		 */
		public void setTelefonoempleador(String value) {
			this.telefonoempleador = value;
		}

		/**
		 * Gets the value of the mesespromedio property.
		 * 
		 */
		public byte getMesespromedio() {
			return mesespromedio;
		}

		/**
		 * Sets the value of the mesespromedio property.
		 * 
		 */
		public void setMesespromedio(byte value) {
			this.mesespromedio = value;
		}

		/**
		 * Gets the value of the fechaentrada property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFechaentrada() {
			return fechaentrada;
		}

		/**
		 * Sets the value of the fechaentrada property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFechaentrada(String value) {
			this.fechaentrada = value;
		}

		/**
		 * Gets the value of the fechasalida property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFechasalida() {
			return fechasalida;
		}

		/**
		 * Sets the value of the fechasalida property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFechasalida(String value) {
			this.fechasalida = value;
		}

		/**
		 * Gets the value of the descripcionempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescripcionempleador() {
			return descripcionempleador;
		}

		/**
		 * Sets the value of the descripcionempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDescripcionempleador(String value) {
			this.descripcionempleador = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="tipo1" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cedtipo1" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="tipo2" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cedtipo2" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "tipo1", "cedtipo1", "tipo2", "cedtipo2" })
	public static class Cedulaspadres {

		@XmlElement(required = true)
		protected String tipo1;
		@XmlElement(required = true)
		protected String cedtipo1;
		@XmlElement(required = true)
		protected String tipo2;
		@XmlElement(required = true)
		protected String cedtipo2;

		/**
		 * Gets the value of the tipo1 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTipo1() {
			return tipo1;
		}

		/**
		 * Sets the value of the tipo1 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTipo1(String value) {
			this.tipo1 = value;
		}

		/**
		 * Gets the value of the cedtipo1 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCedtipo1() {
			return cedtipo1;
		}

		/**
		 * Sets the value of the cedtipo1 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCedtipo1(String value) {
			this.cedtipo1 = value;
		}

		/**
		 * Gets the value of the tipo2 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTipo2() {
			return tipo2;
		}

		/**
		 * Sets the value of the tipo2 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTipo2(String value) {
			this.tipo2 = value;
		}

		/**
		 * Gets the value of the cedtipo2 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCedtipo2() {
			return cedtipo2;
		}

		/**
		 * Sets the value of the cedtipo2 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCedtipo2(String value) {
			this.cedtipo2 = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="cedula" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="primernombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="segundonombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="primerapellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="segundoapellido" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="nombreconyuge" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="nombrepadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="nombremadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="profesion" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="nacionalidad" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="dianacimiento" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="mesnacimiento" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="anionacimiento" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="estadocivil" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="genero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="diamatrimonio" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="mesmatrimonio" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="aniomatrimonio" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="diadefuncion" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="mesdefuncion" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="aniodefuncion" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "cedula", "primernombre", "segundonombre", "primerapellido", "segundoapellido",
			"nombreconyuge", "nombrepadre", "nombremadre", "profesion", "nacionalidad", "dianacimiento",
			"mesnacimiento", "anionacimiento", "estadocivil", "genero", "diamatrimonio", "mesmatrimonio",
			"aniomatrimonio", "diadefuncion", "mesdefuncion", "aniodefuncion" })
	public static class Civil {

		protected String cedula;
		@XmlElement(required = true)
		protected String primernombre;
		@XmlElement(required = true)
		protected String segundonombre;
		@XmlElement(required = true)
		protected String primerapellido;
		@XmlElement(required = true)
		protected String segundoapellido;
		@XmlElement(required = true)
		protected String nombreconyuge;
		@XmlElement(required = true)
		protected String nombrepadre;
		@XmlElement(required = true)
		protected String nombremadre;
		@XmlElement(required = true)
		protected String profesion;
		protected short nacionalidad;
		protected byte dianacimiento;
		protected byte mesnacimiento;
		protected short anionacimiento;
		protected byte estadocivil;
		protected byte genero;
		@XmlElement(required = true)
		protected String diamatrimonio;
		@XmlElement(required = true)
		protected String mesmatrimonio;
		@XmlElement(required = true)
		protected String aniomatrimonio;
		@XmlElement(required = true)
		protected String diadefuncion;
		@XmlElement(required = true)
		protected String mesdefuncion;
		@XmlElement(required = true)
		protected String aniodefuncion;

		/**
		 * Gets the value of the cedula property.
		 * 
		 */
		public String getCedula() {
			return cedula;
		}

		/**
		 * Sets the value of the cedula property.
		 * 
		 */
		public void setCedula(String value) {
			this.cedula = value;
		}

		/**
		 * Gets the value of the primernombre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPrimernombre() {
			return primernombre;
		}

		/**
		 * Sets the value of the primernombre property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setPrimernombre(String value) {
			this.primernombre = value;
		}

		/**
		 * Gets the value of the segundonombre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSegundonombre() {
			return segundonombre;
		}

		/**
		 * Sets the value of the segundonombre property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSegundonombre(String value) {
			this.segundonombre = value;
		}

		/**
		 * Gets the value of the primerapellido property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPrimerapellido() {
			return primerapellido;
		}

		/**
		 * Sets the value of the primerapellido property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setPrimerapellido(String value) {
			this.primerapellido = value;
		}

		/**
		 * Gets the value of the segundoapellido property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSegundoapellido() {
			return segundoapellido;
		}

		/**
		 * Sets the value of the segundoapellido property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSegundoapellido(String value) {
			this.segundoapellido = value;
		}

		/**
		 * Gets the value of the nombreconyuge property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombreconyuge() {
			return nombreconyuge;
		}

		/**
		 * Sets the value of the nombreconyuge property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombreconyuge(String value) {
			this.nombreconyuge = value;
		}

		/**
		 * Gets the value of the nombrepadre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombrepadre() {
			return nombrepadre;
		}

		/**
		 * Sets the value of the nombrepadre property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombrepadre(String value) {
			this.nombrepadre = value;
		}

		/**
		 * Gets the value of the nombremadre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombremadre() {
			return nombremadre;
		}

		/**
		 * Sets the value of the nombremadre property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombremadre(String value) {
			this.nombremadre = value;
		}

		/**
		 * Gets the value of the profesion property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProfesion() {
			return profesion;
		}

		/**
		 * Sets the value of the profesion property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProfesion(String value) {
			this.profesion = value;
		}

		/**
		 * Gets the value of the nacionalidad property.
		 * 
		 */
		public short getNacionalidad() {
			return nacionalidad;
		}

		/**
		 * Sets the value of the nacionalidad property.
		 * 
		 */
		public void setNacionalidad(short value) {
			this.nacionalidad = value;
		}

		/**
		 * Gets the value of the dianacimiento property.
		 * 
		 */
		public byte getDianacimiento() {
			return dianacimiento;
		}

		/**
		 * Sets the value of the dianacimiento property.
		 * 
		 */
		public void setDianacimiento(byte value) {
			this.dianacimiento = value;
		}

		/**
		 * Gets the value of the mesnacimiento property.
		 * 
		 */
		public byte getMesnacimiento() {
			return mesnacimiento;
		}

		/**
		 * Sets the value of the mesnacimiento property.
		 * 
		 */
		public void setMesnacimiento(byte value) {
			this.mesnacimiento = value;
		}

		/**
		 * Gets the value of the anionacimiento property.
		 * 
		 */
		public short getAnionacimiento() {
			return anionacimiento;
		}

		/**
		 * Sets the value of the anionacimiento property.
		 * 
		 */
		public void setAnionacimiento(short value) {
			this.anionacimiento = value;
		}

		/**
		 * Gets the value of the estadocivil property.
		 * 
		 */
		public byte getEstadocivil() {
			return estadocivil;
		}

		/**
		 * Sets the value of the estadocivil property.
		 * 
		 */
		public void setEstadocivil(byte value) {
			this.estadocivil = value;
		}

		/**
		 * Gets the value of the genero property.
		 * 
		 */
		public byte getGenero() {
			return genero;
		}

		/**
		 * Sets the value of the genero property.
		 * 
		 */
		public void setGenero(byte value) {
			this.genero = value;
		}

		/**
		 * Gets the value of the diamatrimonio property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDiamatrimonio() {
			return diamatrimonio;
		}

		/**
		 * Sets the value of the diamatrimonio property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDiamatrimonio(String value) {
			this.diamatrimonio = value;
		}

		/**
		 * Gets the value of the mesmatrimonio property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMesmatrimonio() {
			return mesmatrimonio;
		}

		/**
		 * Sets the value of the mesmatrimonio property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setMesmatrimonio(String value) {
			this.mesmatrimonio = value;
		}

		/**
		 * Gets the value of the aniomatrimonio property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAniomatrimonio() {
			return aniomatrimonio;
		}

		/**
		 * Sets the value of the aniomatrimonio property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAniomatrimonio(String value) {
			this.aniomatrimonio = value;
		}

		/**
		 * Gets the value of the diadefuncion property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDiadefuncion() {
			return diadefuncion;
		}

		/**
		 * Sets the value of the diadefuncion property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDiadefuncion(String value) {
			this.diadefuncion = value;
		}

		/**
		 * Gets the value of the mesdefuncion property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getMesdefuncion() {
			return mesdefuncion;
		}

		/**
		 * Sets the value of the mesdefuncion property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setMesdefuncion(String value) {
			this.mesdefuncion = value;
		}

		/**
		 * Gets the value of the aniodefuncion property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAniodefuncion() {
			return aniodefuncion;
		}

		/**
		 * Sets the value of the aniodefuncion property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAniodefuncion(String value) {
			this.aniodefuncion = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="tel1" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="tel2" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="tel3" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="tel4" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="tel5" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "tel1", "tel2", "tel3", "tel4", "tel5", "provincia", "canton", "parroquia",
			"direccion" })
	public static class Contactabilidad {

		protected String tel1;
		protected String tel2;
		@XmlElement(required = true)
		protected String tel3;
		@XmlElement(required = true)
		protected String tel4;
		@XmlElement(required = true)
		protected String tel5;
		@XmlElement(required = true)
		protected String provincia;
		@XmlElement(required = true)
		protected String canton;
		@XmlElement(required = true)
		protected String parroquia;
		@XmlElement(required = true)
		protected String direccion;

		/**
		 * Gets the value of the tel1 property.
		 * 
		 */
		public String getTel1() {
			return tel1;
		}

		/**
		 * Sets the value of the tel1 property.
		 * 
		 */
		public void setTel1(String value) {
			this.tel1 = value;
		}

		/**
		 * Gets the value of the tel2 property.
		 * 
		 */
		public String getTel2() {
			return tel2;
		}

		/**
		 * Sets the value of the tel2 property.
		 * 
		 */
		public void setTel2(String value) {
			this.tel2 = value;
		}

		/**
		 * Gets the value of the tel3 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTel3() {
			return tel3;
		}

		/**
		 * Sets the value of the tel3 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTel3(String value) {
			this.tel3 = value;
		}

		/**
		 * Gets the value of the tel4 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTel4() {
			return tel4;
		}

		/**
		 * Sets the value of the tel4 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTel4(String value) {
			this.tel4 = value;
		}

		/**
		 * Gets the value of the tel5 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getTel5() {
			return tel5;
		}

		/**
		 * Sets the value of the tel5 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setTel5(String value) {
			this.tel5 = value;
		}

		/**
		 * Gets the value of the provincia property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProvincia() {
			return provincia;
		}

		/**
		 * Sets the value of the provincia property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProvincia(String value) {
			this.provincia = value;
		}

		/**
		 * Gets the value of the canton property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCanton() {
			return canton;
		}

		/**
		 * Sets the value of the canton property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCanton(String value) {
			this.canton = value;
		}

		/**
		 * Gets the value of the parroquia property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getParroquia() {
			return parroquia;
		}

		/**
		 * Sets the value of the parroquia property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setParroquia(String value) {
			this.parroquia = value;
		}

		/**
		 * Gets the value of the direccion property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDireccion() {
			return direccion;
		}

		/**
		 * Sets the value of the direccion property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDireccion(String value) {
			this.direccion = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="conyugenombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "conyugenombre" })
	public static class Conyuge {

		@XmlElement(required = true)
		protected String conyugenombre;

		/**
		 * Gets the value of the conyugenombre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getConyugenombre() {
			return conyugenombre;
		}

		/**
		 * Sets the value of the conyugenombre property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setConyugenombre(String value) {
			this.conyugenombre = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="conyugecedula" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "conyugecedula" })
	public static class Conyugecedula {

		@XmlElement(required = true)
		protected String conyugecedula;

		/**
		 * Gets the value of the conyugecedula property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getConyugecedula() {
			return conyugecedula;
		}

		/**
		 * Sets the value of the conyugecedula property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setConyugecedula(String value) {
			this.conyugecedula = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="hijo1" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hijo2" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hijo3" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hijo4" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hijo5" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hijo6" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hijo7" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="hijo8" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "hijo1", "hijo2", "hijo3", "hijo4", "hijo5", "hijo6", "hijo7", "hijo8" })
	public static class Hijos {

		@XmlElement(required = true)
		protected String hijo1;
		@XmlElement(required = true)
		protected String hijo2;
		@XmlElement(required = true)
		protected String hijo3;
		@XmlElement(required = true)
		protected String hijo4;
		@XmlElement(required = true)
		protected String hijo5;
		@XmlElement(required = true)
		protected String hijo6;
		@XmlElement(required = true)
		protected String hijo7;
		@XmlElement(required = true)
		protected String hijo8;

		/**
		 * Gets the value of the hijo1 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo1() {
			return hijo1;
		}

		/**
		 * Sets the value of the hijo1 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo1(String value) {
			this.hijo1 = value;
		}

		/**
		 * Gets the value of the hijo2 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo2() {
			return hijo2;
		}

		/**
		 * Sets the value of the hijo2 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo2(String value) {
			this.hijo2 = value;
		}

		/**
		 * Gets the value of the hijo3 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo3() {
			return hijo3;
		}

		/**
		 * Sets the value of the hijo3 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo3(String value) {
			this.hijo3 = value;
		}

		/**
		 * Gets the value of the hijo4 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo4() {
			return hijo4;
		}

		/**
		 * Sets the value of the hijo4 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo4(String value) {
			this.hijo4 = value;
		}

		/**
		 * Gets the value of the hijo5 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo5() {
			return hijo5;
		}

		/**
		 * Sets the value of the hijo5 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo5(String value) {
			this.hijo5 = value;
		}

		/**
		 * Gets the value of the hijo6 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo6() {
			return hijo6;
		}

		/**
		 * Sets the value of the hijo6 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo6(String value) {
			this.hijo6 = value;
		}

		/**
		 * Gets the value of the hijo7 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo7() {
			return hijo7;
		}

		/**
		 * Sets the value of the hijo7 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo7(String value) {
			this.hijo7 = value;
		}

		/**
		 * Gets the value of the hijo8 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getHijo8() {
			return hijo8;
		}

		/**
		 * Sets the value of the hijo8 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setHijo8(String value) {
			this.hijo8 = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="nombrepadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="nombremadre" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "nombrepadre", "nombremadre" })
	public static class Padres {

		@XmlElement(required = true)
		protected String nombrepadre;
		@XmlElement(required = true)
		protected String nombremadre;

		/**
		 * Gets the value of the nombrepadre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombrepadre() {
			return nombrepadre;
		}

		/**
		 * Sets the value of the nombrepadre property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombrepadre(String value) {
			this.nombrepadre = value;
		}

		/**
		 * Gets the value of the nombremadre property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombremadre() {
			return nombremadre;
		}

		/**
		 * Sets the value of the nombremadre property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombremadre(String value) {
			this.nombremadre = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="nombreempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="rucempleador" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *         &lt;element name="descripcionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="direccionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="actividadempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="provinciaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="parroquiaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cantonempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="fechaentradaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="fechasalidaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cargoempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="salarioempleador" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="telefonoempleador" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "nombreempleador", "rucempleador", "descripcionempleador", "direccionempleador",
			"actividadempleador", "provinciaempleador", "parroquiaempleador", "cantonempleador",
			"fechaentradaempleador", "fechasalidaempleador", "cargoempleador", "salarioempleador",
			"telefonoempleador" })
	public static class PrimeroAnterior {

		@XmlElement(required = true)
		protected String nombreempleador;
		protected String rucempleador;
		@XmlElement(required = true)
		protected String descripcionempleador;
		@XmlElement(required = true)
		protected String direccionempleador;
		@XmlElement(required = true)
		protected String actividadempleador;
		@XmlElement(required = true)
		protected String provinciaempleador;
		@XmlElement(required = true)
		protected String parroquiaempleador;
		@XmlElement(required = true)
		protected String cantonempleador;
		@XmlElement(required = true)
		protected String fechaentradaempleador;
		@XmlElement(required = true)
		protected String fechasalidaempleador;
		@XmlElement(required = true)
		protected String cargoempleador;
		protected short salarioempleador;
		protected String telefonoempleador;

		/**
		 * Gets the value of the nombreempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombreempleador() {
			return nombreempleador;
		}

		/**
		 * Sets the value of the nombreempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombreempleador(String value) {
			this.nombreempleador = value;
		}

		/**
		 * Gets the value of the rucempleador property.
		 * 
		 */
		public String getRucempleador() {
			return rucempleador;
		}

		/**
		 * Sets the value of the rucempleador property.
		 * 
		 */
		public void setRucempleador(String value) {
			this.rucempleador = value;
		}

		/**
		 * Gets the value of the descripcionempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescripcionempleador() {
			return descripcionempleador;
		}

		/**
		 * Sets the value of the descripcionempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDescripcionempleador(String value) {
			this.descripcionempleador = value;
		}

		/**
		 * Gets the value of the direccionempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDireccionempleador() {
			return direccionempleador;
		}

		/**
		 * Sets the value of the direccionempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDireccionempleador(String value) {
			this.direccionempleador = value;
		}

		/**
		 * Gets the value of the actividadempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getActividadempleador() {
			return actividadempleador;
		}

		/**
		 * Sets the value of the actividadempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setActividadempleador(String value) {
			this.actividadempleador = value;
		}

		/**
		 * Gets the value of the provinciaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProvinciaempleador() {
			return provinciaempleador;
		}

		/**
		 * Sets the value of the provinciaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProvinciaempleador(String value) {
			this.provinciaempleador = value;
		}

		/**
		 * Gets the value of the parroquiaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getParroquiaempleador() {
			return parroquiaempleador;
		}

		/**
		 * Sets the value of the parroquiaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setParroquiaempleador(String value) {
			this.parroquiaempleador = value;
		}

		/**
		 * Gets the value of the cantonempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCantonempleador() {
			return cantonempleador;
		}

		/**
		 * Sets the value of the cantonempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCantonempleador(String value) {
			this.cantonempleador = value;
		}

		/**
		 * Gets the value of the fechaentradaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFechaentradaempleador() {
			return fechaentradaempleador;
		}

		/**
		 * Sets the value of the fechaentradaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFechaentradaempleador(String value) {
			this.fechaentradaempleador = value;
		}

		/**
		 * Gets the value of the fechasalidaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFechasalidaempleador() {
			return fechasalidaempleador;
		}

		/**
		 * Sets the value of the fechasalidaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFechasalidaempleador(String value) {
			this.fechasalidaempleador = value;
		}

		/**
		 * Gets the value of the cargoempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCargoempleador() {
			return cargoempleador;
		}

		/**
		 * Sets the value of the cargoempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCargoempleador(String value) {
			this.cargoempleador = value;
		}

		/**
		 * Gets the value of the salarioempleador property.
		 * 
		 */
		public short getSalarioempleador() {
			return salarioempleador;
		}

		/**
		 * Sets the value of the salarioempleador property.
		 * 
		 */
		public void setSalarioempleador(short value) {
			this.salarioempleador = value;
		}

		/**
		 * Gets the value of the telefonoempleador property.
		 * 
		 */
		public String getTelefonoempleador() {
			return telefonoempleador;
		}

		/**
		 * Sets the value of the telefonoempleador property.
		 * 
		 */
		public void setTelefonoempleador(String value) {
			this.telefonoempleador = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="nombreempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="rucempleador" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *         &lt;element name="descripcionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="direccionempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="actividadempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="provinciaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="parroquiaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cantonempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="fechaentradaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="fechasalidaempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="cargoempleador" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="salarioempleador" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="telefonoempleador" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "nombreempleador", "rucempleador", "descripcionempleador", "direccionempleador",
			"actividadempleador", "provinciaempleador", "parroquiaempleador", "cantonempleador",
			"fechaentradaempleador", "fechasalidaempleador", "cargoempleador", "salarioempleador",
			"telefonoempleador" })
	public static class SegundoAnterior {

		@XmlElement(required = true)
		protected String nombreempleador;
		protected String rucempleador;
		@XmlElement(required = true)
		protected String descripcionempleador;
		@XmlElement(required = true)
		protected String direccionempleador;
		@XmlElement(required = true)
		protected String actividadempleador;
		@XmlElement(required = true)
		protected String provinciaempleador;
		@XmlElement(required = true)
		protected String parroquiaempleador;
		@XmlElement(required = true)
		protected String cantonempleador;
		@XmlElement(required = true)
		protected String fechaentradaempleador;
		@XmlElement(required = true)
		protected String fechasalidaempleador;
		@XmlElement(required = true)
		protected String cargoempleador;
		protected short salarioempleador;
		protected String telefonoempleador;

		/**
		 * Gets the value of the nombreempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombreempleador() {
			return nombreempleador;
		}

		/**
		 * Sets the value of the nombreempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombreempleador(String value) {
			this.nombreempleador = value;
		}

		/**
		 * Gets the value of the rucempleador property.
		 * 
		 */
		public String getRucempleador() {
			return rucempleador;
		}

		/**
		 * Sets the value of the rucempleador property.
		 * 
		 */
		public void setRucempleador(String value) {
			this.rucempleador = value;
		}

		/**
		 * Gets the value of the descripcionempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDescripcionempleador() {
			return descripcionempleador;
		}

		/**
		 * Sets the value of the descripcionempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDescripcionempleador(String value) {
			this.descripcionempleador = value;
		}

		/**
		 * Gets the value of the direccionempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDireccionempleador() {
			return direccionempleador;
		}

		/**
		 * Sets the value of the direccionempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDireccionempleador(String value) {
			this.direccionempleador = value;
		}

		/**
		 * Gets the value of the actividadempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getActividadempleador() {
			return actividadempleador;
		}

		/**
		 * Sets the value of the actividadempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setActividadempleador(String value) {
			this.actividadempleador = value;
		}

		/**
		 * Gets the value of the provinciaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProvinciaempleador() {
			return provinciaempleador;
		}

		/**
		 * Sets the value of the provinciaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setProvinciaempleador(String value) {
			this.provinciaempleador = value;
		}

		/**
		 * Gets the value of the parroquiaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getParroquiaempleador() {
			return parroquiaempleador;
		}

		/**
		 * Sets the value of the parroquiaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setParroquiaempleador(String value) {
			this.parroquiaempleador = value;
		}

		/**
		 * Gets the value of the cantonempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCantonempleador() {
			return cantonempleador;
		}

		/**
		 * Sets the value of the cantonempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCantonempleador(String value) {
			this.cantonempleador = value;
		}

		/**
		 * Gets the value of the fechaentradaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFechaentradaempleador() {
			return fechaentradaempleador;
		}

		/**
		 * Sets the value of the fechaentradaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFechaentradaempleador(String value) {
			this.fechaentradaempleador = value;
		}

		/**
		 * Gets the value of the fechasalidaempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFechasalidaempleador() {
			return fechasalidaempleador;
		}

		/**
		 * Sets the value of the fechasalidaempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFechasalidaempleador(String value) {
			this.fechasalidaempleador = value;
		}

		/**
		 * Gets the value of the cargoempleador property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCargoempleador() {
			return cargoempleador;
		}

		/**
		 * Sets the value of the cargoempleador property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCargoempleador(String value) {
			this.cargoempleador = value;
		}

		/**
		 * Gets the value of the salarioempleador property.
		 * 
		 */
		public short getSalarioempleador() {
			return salarioempleador;
		}

		/**
		 * Sets the value of the salarioempleador property.
		 * 
		 */
		public void setSalarioempleador(short value) {
			this.salarioempleador = value;
		}

		/**
		 * Gets the value of the telefonoempleador property.
		 * 
		 */
		public String getTelefonoempleador() {
			return telefonoempleador;
		}

		/**
		 * Sets the value of the telefonoempleador property.
		 * 
		 */
		public void setTelefonoempleador(String value) {
			this.telefonoempleador = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="rucpersonanatual" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *         &lt;element name="razonsocial" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="nombrefantasia" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="actividad" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="calle" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="interseccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="referencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="obligado" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *         &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *         &lt;element name="fechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="suspension" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="reinicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="telefono" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "rucpersonanatual", "razonsocial", "nombrefantasia", "actividad", "calle",
			"numero", "interseccion", "referencia", "obligado", "provincia", "canton", "parroquia", "fechainicio",
			"suspension", "reinicio", "telefono" })
	public static class Sri {

		protected String rucpersonanatual;
		@XmlElement(required = true)
		protected String razonsocial;
		@XmlElement(required = true)
		protected String nombrefantasia;
		@XmlElement(required = true)
		protected String actividad;
		@XmlElement(required = true)
		protected String calle;
		@XmlElement(required = true)
		protected String numero;
		@XmlElement(required = true)
		protected String interseccion;
		@XmlElement(required = true)
		protected String referencia;
		@XmlElement(required = true)
		protected String obligado;
		protected String provincia;
		protected String canton;
		protected String parroquia;
		@XmlElement(required = true)
		protected String fechainicio;
		@XmlElement(required = true)
		protected String suspension;
		@XmlElement(required = true)
		protected String reinicio;
		protected String telefono;

		/**
		 * Gets the value of the rucpersonanatual property.
		 * 
		 */
		public String getRucpersonanatual() {
			return rucpersonanatual;
		}

		/**
		 * Sets the value of the rucpersonanatual property.
		 * 
		 */
		public void setRucpersonanatual(String value) {
			this.rucpersonanatual = value;
		}

		/**
		 * Gets the value of the razonsocial property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getRazonsocial() {
			return razonsocial;
		}

		/**
		 * Sets the value of the razonsocial property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setRazonsocial(String value) {
			this.razonsocial = value;
		}

		/**
		 * Gets the value of the nombrefantasia property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNombrefantasia() {
			return nombrefantasia;
		}

		/**
		 * Sets the value of the nombrefantasia property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNombrefantasia(String value) {
			this.nombrefantasia = value;
		}

		/**
		 * Gets the value of the actividad property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getActividad() {
			return actividad;
		}

		/**
		 * Sets the value of the actividad property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setActividad(String value) {
			this.actividad = value;
		}

		/**
		 * Gets the value of the calle property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCalle() {
			return calle;
		}

		/**
		 * Sets the value of the calle property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCalle(String value) {
			this.calle = value;
		}

		/**
		 * Gets the value of the numero property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNumero() {
			return numero;
		}

		/**
		 * Sets the value of the numero property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNumero(String value) {
			this.numero = value;
		}

		/**
		 * Gets the value of the interseccion property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getInterseccion() {
			return interseccion;
		}

		/**
		 * Sets the value of the interseccion property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setInterseccion(String value) {
			this.interseccion = value;
		}

		/**
		 * Gets the value of the referencia property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getReferencia() {
			return referencia;
		}

		/**
		 * Sets the value of the referencia property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setReferencia(String value) {
			this.referencia = value;
		}

		/**
		 * Gets the value of the obligado property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getObligado() {
			return obligado;
		}

		/**
		 * Sets the value of the obligado property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setObligado(String value) {
			this.obligado = value;
		}

		/**
		 * Gets the value of the provincia property.
		 * 
		 */
		public String getProvincia() {
			return provincia;
		}

		/**
		 * Sets the value of the provincia property.
		 * 
		 */
		public void setProvincia(String value) {
			this.provincia = value;
		}

		/**
		 * Gets the value of the canton property.
		 * 
		 */
		public String getCanton() {
			return canton;
		}

		/**
		 * Sets the value of the canton property.
		 * 
		 */
		public void setCanton(String value) {
			this.canton = value;
		}

		/**
		 * Gets the value of the parroquia property.
		 * 
		 */
		public String getParroquia() {
			return parroquia;
		}

		/**
		 * Sets the value of the parroquia property.
		 * 
		 */
		public void setParroquia(String value) {
			this.parroquia = value;
		}

		/**
		 * Gets the value of the fechainicio property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFechainicio() {
			return fechainicio;
		}

		/**
		 * Sets the value of the fechainicio property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFechainicio(String value) {
			this.fechainicio = value;
		}

		/**
		 * Gets the value of the suspension property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSuspension() {
			return suspension;
		}

		/**
		 * Sets the value of the suspension property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSuspension(String value) {
			this.suspension = value;
		}

		/**
		 * Gets the value of the reinicio property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getReinicio() {
			return reinicio;
		}

		/**
		 * Sets the value of the reinicio property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setReinicio(String value) {
			this.reinicio = value;
		}

		/**
		 * Gets the value of the telefono property.
		 * 
		 */
		public String getTelefono() {
			return telefono;
		}

		/**
		 * Sets the value of the telefono property.
		 * 
		 */
		public void setTelefono(String value) {
			this.telefono = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="placa" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "placa" })
	public static class Vehicular {

		@XmlElement(required = true)
		protected String placa;

		/**
		 * Gets the value of the placa property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPlaca() {
			return placa;
		}

		/**
		 * Sets the value of the placa property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setPlaca(String value) {
			this.placa = value;
		}

	}

}
