<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="InsertMPersonaWsImplService" targetNamespace="http://impl.ws.sise.equivida.com/" xmlns:ns1="http://ws.sise.equivida.com/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://impl.ws.sise.equivida.com/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="http://localhost:8080/sise-servicio/InsertMPersonaWsImpl?wsdl=InsertMPersonaWs.wsdl" namespace="http://ws.sise.equivida.com/">
    </wsdl:import>
  <wsdl:binding name="InsertMPersonaWsImplServiceSoapBinding" type="ns1:InsertMPersonaWs">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ws_sise_insert_mpersona">
      <soap:operation soapAction="" style="rpc" />
      <wsdl:input name="ws_sise_insert_mpersona">
        <soap:body namespace="http://ws.sise.equivida.com/" use="literal" />
      </wsdl:input>
      <wsdl:output name="ws_sise_insert_mpersonaResponse">
        <soap:body namespace="http://ws.sise.equivida.com/" use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="InsertMPersonaWsImplService">
    <wsdl:port binding="tns:InsertMPersonaWsImplServiceSoapBinding" name="InsertMPersonaWsImplPort">
      <soap:address location="http://localhost:8080/sise-servicio/InsertMPersonaWsImpl" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>